
networks:
  inception-network:
    name: inception-network

services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: on-failure
    networks:
      - inception-network
